from ISE_Transformer.envs.BetaAviary import BetaAviary
from ISE_Transformer.envs.CtrlAviary import CtrlAviary
from ISE_Transformer.envs.HoverAviary import HoverAviary
from ISE_Transformer.envs.MultiHoverAviary import MultiHoverAviary
from ISE_Transformer.envs.VelocityAviary import VelocityAviary
from ISE_Transformer.envs.coverage_lidar_aviary import CoverageAviary